import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import { Theme } from '@radix-ui/themes';
import cn from '@/utils/cn';
import { Toaster } from 'sonner';

import '@/app/styles/tailwind.css';
import '@/app/styles/radix.css';
import '@radix-ui/themes/styles.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='dark'>
      <body
        className={cn(
          GeistSans.variable,
          GeistMono.variable,
          'w-full min-h-[100dvh] bg-black font-sans'
        )}
      >
        <Toaster />

        <Theme radius='large'>
          {children}
        </Theme>
      </body>
    </html>
  );
}
