const Endpoints = {
  AddSocial: slug => `/profiles/${slug}`,
  ApproveBot: id => `/bots/${id}/approve`,
  ApproveBotReview: (botId, reviewId) => `/bots/${botId}/reviews/${reviewId}/approve`,
  ApproveEmoji: id => `/emojis/${id}/approve`,
  ApproveServerReview: (serverId, reviewId) => `/servers/${serverId}/reviews/${reviewId}/approve`,
  ApproveSound: id => `/sounds/${id}/approve`,
  ApproveTemplate: id => `/templates/${id}/approve`,
  ApproveTheme: id => `/themes/${id}/approve`,
  CheckSlugAvailability: '/profiles/check-slug-availability',
  CreateApiKey: id => `/bots/${id}/api-key`,
  CreateBot: id => `/bots/${id}`,
  CreateBotReview: id => `/bots/${id}/reviews`,
  CreateCheckout: '/payments/checkout',
  CreateEmoji: '/emojis',
  CreateExtraOwner: botId => `/bots/${botId}/extra-owners`,
  CreateLink: '/links',
  CreateProfile: '/profiles',
  CreateQuarantine: '/quarantines',
  CreateReminder: id => `/servers/${id}/reminder`,
  CreateReport: '/reports',
  CreateSound: '/sounds',
  CreateStandedOutCheckout: '/payments/checkout',
  CreateTemplate: '/templates',
  CreateTheme: '/themes',
  CreateTripledVotesCheckout: '/payments/checkout',
  DeleteApiKey: id => `/bots/${id}/api-key`,
  DeleteBot: id => `/bots/${id}`,
  DeleteBotDenyRecord: id => `/bot-denies/${id}`,
  DeleteBotReview: (botId, reviewId) => `/bots/${botId}/reviews/${reviewId}`,
  DeleteBotTimeout: (botId, userId) => `/bots/${botId}/voters/${userId}/timeout`,
  DeleteBotWebhookSettings: id => `/bots/${id}/webhook-settings`,
  DeleteEmoji: id => `/emojis/${id}/delete`,
  DeleteLink: id => `/links/${id}`,
  DeleteProfile: slug => `/profiles/${slug}/delete`,
  DeleteQuarantineRecord: id => `/quarantines/${id}`,
  DeleteServer: id => `/servers/${id}`,
  DeleteServerReview: (serverId, reviewId) => `/servers/${serverId}/reviews/${reviewId}`,
  DeleteServerTimeout: (serverId, userId) => `/servers/${serverId}/voters/${userId}/timeout`,
  DeleteServerWebhookSettings: id => `/servers/${id}/webhook-settings`,
  DeleteSocial: (slug, socialId) => `/profiles/${slug}/socials/delete/${socialId}`,
  DeleteSound: id => `/sounds/${id}`,
  DeleteTemplate: id => `/templates/${id}`,
  DeleteTheme: id => `/themes/${id}`,
  DenyBot: id => `/bots/${id}/deny`,
  DenyEmoji: id => `/emojis/${id}/deny`,
  DenyReview: (botId, reviewId) => `/bots/${botId}/reviews/${reviewId}/deny`,
  DenyServerReview: (serverId, reviewId) => `/servers/${serverId}/reviews/${reviewId}/deny`,
  DenySound: id => `/sounds/${id}/deny`,
  DenyTemplate: id => `/templates/${id}/deny`,
  DenyTheme: id => `/themes/${id}/deny`,
  EditBot: id => `/bots/${id}`,
  EditProfile: slug => `/profiles/${slug}`,
  FetchBotReviews: id => `/bots/${id}/reviews`,
  FetchBots: '/bots/search',
  FetchBotVoters: id => `/bots/${id}/voters`,
  FetchEmojis: '/emojis/search',
  FetchPresences: 'https://lantern.rest/api/v1/users',
  FetchServerReviews: id => `/servers/${id}/reviews`,
  FetchServers: '/servers/search',
  FetchServerVoters: id => `/servers/${id}/voters`,
  FetchSounds: '/sounds/search',
  FetchTemplateDetails: id => `/templates/details/${id}`,
  FetchTemplates: '/templates/search',
  FetchThemes: '/themes/search',
  GetApplicationsEntitlementsScopeGranted: '/auth/@me/applications-entitlements-scope-granted',
  GetAuthenticatedUser: '/auth/@me',
  GetBot: id => `/bots/${id}`,
  GetBotMetadata: id => `/bots/${id}/metadata`,
  GetBotStats: '/bots/stats',
  GetDashboardData: '/dashboard',
  GetData: '/auth/@me/data',
  GetEmoji: (id, isPack) => `/emojis/${isPack ? 'packages/' : ''}${id}`,
  GetEmojiMetadata: (id, isPack) => `/emojis/${isPack ? 'packages/' : ''}${id}/metadata`,
  GetEmojiUploadableGuilds: '/auth/@me/emoji-uploadable-guilds',
  GetExtraOwners: id => `/bots/${id}/extra-owners`,
  GetHashes: id => `/users/${id}/hashes`,
  GetPlans: '/payments/plans',
  GetProfile: slug => `/profiles/${slug}`,
  GetProfileMetadata: id => `/profiles/${id}/metadata`,
  GetSoundUploadableGuilds: '/auth/@me/sound-uploadable-guilds',
  GetStatus: '/status',
  GetUser: id => `/users/${id}`,
  IncrementEmojiDownloads: (id, isPack) => `/emojis/${isPack ? 'packages/' : ''}${id}/downloads`,
  IncrementSoundDownloads: id => `/sounds/${id}/downloads`,
  IncrementViews: slug => `/profiles/${slug}/views`,
  LikeProfile: slug => `/profiles/${slug}/like`,
  LikeSound: id => `/sounds/${id}/like`,
  Logout: '/auth/logout',
  PatchProfileVerify: slug => `/profiles/${slug}`,
  RemoveExtraOwner: (botId, userId) => `/bots/${botId}/extra-owners/${userId}`,
  RestoreBot: id => `/bot-denies/${id}/restore`,
  Server: id => `/servers/${id}`,
  ServerMetadata: id => `/servers/${id}/metadata`,
  SetBotWebhookSettings: id => `/bots/${id}/webhook-settings`,
  SetServerWebhookSettings: id => `/servers/${id}/webhook-settings`,
  SoundMetadata: id => `/sounds/${id}/metadata`,
  Sounds: id => `/sounds/${id}`,
  SyncLemonSqueezyPlans: '/payments/plans/sync',
  TemplateMetadata: id => `/templates/${id}/metadata`,
  Templates: id => `/templates/${id}`,
  TestBotWebhook: id => `/bots/${id}/test-webhook`,
  TestServerWebhook: id => `/servers/${id}/test-webhook`,
  ThemeMetadata: themeId => `/themes/${themeId}/metadata`,
  Themes: id => `/themes/${id}`,
  UploadEmojiToGuild: (id, packIndex) => `/emojis/${packIndex !== false ? 'packages/' : ''}${id}/upload-to-guild`,
  UploadSoundToGuild: id => `/sounds/${id}/upload-to-guild`,
  VoteBot: id => `/bots/${id}/vote`,
  VoteServer: id => `/servers/${id}/vote`
};

export default Endpoints;