name: "ESLint: client"

on:
  pull_request:
    paths:
      - 'client/**'

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies to /client
        run: |
          cd client
          npm install
          
      - name: Run lint script on /client
        run: |
          cd client
          npm run lint